NUM_USERS=1000
MAX_WORKERS=30
REQUEST_DELAY=0.02
QUERY_RANDOM_SEED = 42
QUERY_WORKLOAD_SIZE = 1000
QUERY_UNIQUE_RATIO = 0.75
QUERY_REPEAT_POOL_SIZE = 50
REPORT_EXPORT_DIR = "reports"
REMOTE_WORKER_TIMEOUT_SECONDS = 180
DEFAULT_REMOTE_WORKER_URLS = (
    "http://127.0.0.1:8001",
    "http://127.0.0.1:8002",
    "http://127.0.0.1:8003",
)
# LLM Configuration
LLM_MODEL_NAME = "google/flan-t5-small"
LLM_MAX_INPUT_TOKENS = 512
LLM_MAX_NEW_TOKENS = 64
LLM_TIMEOUT_SECONDS = 30
LLM_CACHE_MAX_SIZE = 1000
LLM_ENABLE_LOGGING = True
# LLM retry configuration
LLM_MAX_RETRIES = 2

# Scheduler response cache
SCHEDULER_RESPONSE_CACHE_MAX_SIZE = 1000
SCHEDULER_CACHE_SIMILARITY_THRESHOLD = 0.85

# RAG Configuration
RAG_EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
RAG_CACHE_MAX_SIZE = 1000
RAG_DEFAULT_TOP_K = 3
RAG_ENABLE_LOGGING = True

# Load balancer configuration
LOAD_BALANCER_STRATEGIES = ("round_robin", "least_connections", "load_aware")
LOAD_BALANCER_DEFAULT_STRATEGY = "load_aware"
LOAD_BALANCER_DEFAULT_GPU_CAPACITY = {
    1: 1.0,  # 100%
    2: 0.7,  # 70%
    3: 0.4,  # 40%
}
LOAD_BALANCER_MIN_GPU_CAPACITY = 0.1
LOAD_BALANCER_QUEUE_WEIGHT = 0.75
LOAD_BALANCER_LATENCY_PENALTY_WEIGHT = 0.25


TEST_USERS = [50, 100, 200, 300, 1000]
TEST_STRATEGIES = ["round_robin", "least_connections", "load_aware"]

# Load modes
NORMAL_LOAD_DELAY = 0.01
BURST_LOAD_DELAY = 0.001
