NUM_USERS=100
MAX_WORKERS=50
REQUEST_DELAY=0.01
# LLM Configuration
LLM_MODEL_NAME = "google/flan-t5-small"
LLM_MAX_INPUT_TOKENS = 512
LLM_MAX_NEW_TOKENS = 64
LLM_TIMEOUT_SECONDS = 15
LLM_CACHE_MAX_SIZE = 1000
LLM_ENABLE_LOGGING = True
# LLM retry configuration
LLM_MAX_RETRIES = 2
# RAG Configuration
RAG_EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
RAG_CACHE_MAX_SIZE = 1000
RAG_DEFAULT_TOP_K = 3
RAG_ENABLE_LOGGING = True