NUM_USERS=100
MAX_WORKERS=50
REQUEST_DELAY=0.01
# LLM Configuration
LLM_MODEL_NAME = "google/flan-t5-small"
LLM_MAX_INPUT_TOKENS = 512
LLM_MAX_NEW_TOKENS = 64
LLM_TIMEOUT_SECONDS = 15
LLM_CACHE_MAX_SIZE = 1000
LLM_ENABLE_LOGGING = True
# LLM retry configuration
LLM_MAX_RETRIES = 2
# RAG Configuration
RAG_EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
RAG_CACHE_MAX_SIZE = 1000
RAG_DEFAULT_TOP_K = 3
RAG_ENABLE_LOGGING = True

# Load balancer configuration
LOAD_BALANCER_STRATEGIES = ("round_robin", "least_connections", "load_aware")
LOAD_BALANCER_DEFAULT_STRATEGY = "load_aware"
LOAD_BALANCER_DEFAULT_GPU_CAPACITY = {
    1: 1.0,  # 100%
    2: 0.7,  # 70%
    3: 0.4,  # 40%
}
LOAD_BALANCER_MIN_GPU_CAPACITY = 0.1
LOAD_BALANCER_QUEUE_WEIGHT = 0.75
LOAD_BALANCER_LATENCY_PENALTY_WEIGHT = 0.25
